/* ══════════════════════════════════════════════════════════════
   ELITE SPORTS SCIENCE — state.js
   Unica fonte di verità per lo stato condiviso.
   Nessun import: tutti gli altri moduli importano da qui.
   ══════════════════════════════════════════════════════════════ */

// ─────────────────────────────────────────────────────────────
// COSTANTI
// ─────────────────────────────────────────────────────────────
export const KEY = 'coachOS_v3';

export const rpeDescs  = { 6:'Recupero leggero', 7:'Fatica moderata', 8:'Impegnativo (2 RIR)', 9:'Molto duro (1 RIR)', 10:'Massimale / Cedimento' };
export const starDescs = { 1:'Pessima', 2:'Sotto tono', 3:'Standard', 4:'Molto buona', 5:'Eccezionale' };

// ytUrl: URL YouTube per il video tutorial (aperto nel modal in-app)
// anatomicalZone: zona anatomica per il sistema infortuni
export const EXERCISE_LIBRARY = [
    // ── COMPOUND PUSH ────────────────────────────────────────
    { id: 'bench_press_bb',    name: 'Bench Press Bilanciere',           trackE1rm: true,  anatomicalZone: 'shoulders', ytUrl: 'https://youtu.be/gRVjAtPip0Y' },
    { id: 'chest_press',       name: 'Chest Press',                      trackE1rm: true,  anatomicalZone: 'shoulders', ytUrl: 'https://youtu.be/xUm0BiZCWlQ' },
    { id: 'incline_bb',        name: 'Incline Bench Press Bilanciere',   trackE1rm: true,  anatomicalZone: 'shoulders', ytUrl: 'https://youtu.be/DbFgADa2PL8' },
    { id: 'incline_db',        name: 'Incline DB Bench Press',           trackE1rm: true,  anatomicalZone: 'shoulders', ytUrl: 'https://youtu.be/8iPEnn-ltC8' },
    { id: 'db_bench_30',       name: 'DB Bench Press Panca 30',          trackE1rm: true,  anatomicalZone: 'shoulders', ytUrl: 'https://youtu.be/VmB1G1K7v94' },
    { id: 'db_bench_flat',     name: 'DB Bench Press Flat',              trackE1rm: true,  anatomicalZone: 'shoulders', ytUrl: 'https://youtu.be/QsYre__-aro' },
    { id: 'shoulder_press',    name: 'Shoulder Press',                   trackE1rm: true,  anatomicalZone: 'shoulders', ytUrl: 'https://youtu.be/qEwKCR5JCog' },
    { id: 'ohp_bb',            name: 'Overhead Press Bilanciere',        trackE1rm: true,  anatomicalZone: 'shoulders', ytUrl: 'https://youtu.be/2yjwXTZQDDI' },
    { id: 'arnold_press',      name: 'Arnold Press',                     trackE1rm: true,  anatomicalZone: 'shoulders', ytUrl: 'https://youtu.be/3N7qz1kE_yA' },
    { id: 'dips_chest',        name: 'Dips (Petto)',                     trackE1rm: true,  anatomicalZone: 'shoulders', ytUrl: 'https://youtu.be/2z8JmcrW-As' },
    { id: 'push_up',           name: 'Elevated Push Up',                 trackE1rm: false, anatomicalZone: 'shoulders', ytUrl: 'https://youtu.be/IODxDxX7oi4' },
    { id: 'push_up_std',       name: 'Push Up',                          trackE1rm: false, anatomicalZone: 'shoulders', ytUrl: 'https://youtu.be/IODxDxX7oi4' },
    { id: 'landmine_press',    name: 'Landmine Press',                   trackE1rm: true,  anatomicalZone: 'shoulders', ytUrl: 'https://youtu.be/MLsP2YjMdbM' },
    { id: 'decline_bench',     name: 'Decline Bench Press Bilanciere',   trackE1rm: true,  anatomicalZone: 'shoulders', ytUrl: 'https://youtu.be/FFyGwcLnDYc' },
    { id: 'decline_db',        name: 'Decline DB Bench Press',           trackE1rm: false, anatomicalZone: 'shoulders', ytUrl: 'https://youtu.be/KYJgQZPwGS8' },
    { id: 'close_grip_bench',  name: 'Close Grip Bench Press',           trackE1rm: true,  anatomicalZone: 'elbows',    ytUrl: 'https://youtu.be/LB6HBNHkavg' },
    { id: 'db_shoulder_press', name: 'DB Shoulder Press',                trackE1rm: true,  anatomicalZone: 'shoulders', ytUrl: 'https://youtu.be/rO_iEImwHyo' },
    { id: 'machine_shoulder_press', name: 'Shoulder Press Machine',      trackE1rm: true,  anatomicalZone: 'shoulders', ytUrl: 'https://youtu.be/BAZkFGeUy5U' },
    { id: 'diamond_push_up',   name: 'Diamond Push-Up',                  trackE1rm: false, anatomicalZone: 'elbows',    ytUrl: 'https://youtu.be/2-OFbQ9GLpE' },
    { id: 'floor_press',       name: 'Floor Press Bilanciere',           trackE1rm: true,  anatomicalZone: '',          ytUrl: 'https://youtu.be/gacJl2rHwtg' },
    { id: 'cable_chest_press', name: 'Cable Chest Press',                trackE1rm: true,  anatomicalZone: 'shoulders', ytUrl: 'https://youtu.be/xUm0BiZCWlQ' },
    { id: 'ring_push_up',      name: 'Ring Push-Up',                     trackE1rm: false, anatomicalZone: '',          ytUrl: 'https://youtu.be/2-OFbQ9GLpE' },
    { id: 'pike_push_up',      name: 'Pike Push-Up',                     trackE1rm: false, anatomicalZone: 'shoulders', ytUrl: 'https://youtu.be/IODxDxX7oi4' },
    { id: 'z_press',           name: 'Z-Press (OHP da terra)',            trackE1rm: true,  anatomicalZone: 'shoulders', ytUrl: 'https://youtu.be/2yjwXTZQDDI' },
    { id: 'svend_press',       name: 'Svend Press',                      trackE1rm: false, anatomicalZone: '',          ytUrl: 'https://youtu.be/eozdVDA78K0' },
    { id: 'jm_press',            name: 'JM Press',                         trackE1rm: true,  anatomicalZone: 'elbows',    ytUrl: 'https://youtu.be/LB6HBNHkavg' },
    { id: 'board_press',         name: 'Board Press',                      trackE1rm: true,  anatomicalZone: '',          ytUrl: 'https://youtu.be/gRVjAtPip0Y' },
    { id: 'db_floor_press',      name: 'DB Floor Press',                   trackE1rm: true,  anatomicalZone: '',          ytUrl: 'https://youtu.be/gacJl2rHwtg' },
    { id: 'incline_cable_press', name: 'Incline Cable Press',              trackE1rm: true,  anatomicalZone: 'shoulders', ytUrl: 'https://youtu.be/eQ_NBB6OBH4' },
    { id: 'wide_push_up',        name: 'Wide Grip Push-Up',                trackE1rm: false, anatomicalZone: '',          ytUrl: 'https://youtu.be/IODxDxX7oi4' },
    { id: 'low_incline_db',      name: 'Low Incline DB Press',             trackE1rm: true,  anatomicalZone: 'shoulders', ytUrl: 'https://youtu.be/8iPEnn-ltC8' },

    // ── COMPOUND PULL ────────────────────────────────────────
    { id: 'lat_machine',       name: 'Lat Machine',                      trackE1rm: true,  anatomicalZone: 'shoulders', ytUrl: 'https://youtu.be/CAwf7n6Luuc' },
    { id: 'pull_up',           name: 'Pull Up',                          trackE1rm: true,  anatomicalZone: 'shoulders', ytUrl: 'https://youtu.be/eGo4IYlbE5g' },
    { id: 'chin_up',           name: 'Chin Up',                          trackE1rm: true,  anatomicalZone: 'shoulders', ytUrl: 'https://youtu.be/brhRXlOhsAM' },
    { id: 'bb_row',            name: 'Barbell Row',                      trackE1rm: true,  anatomicalZone: 'lowerback',  ytUrl: 'https://youtu.be/T3N-TO4reLQ' },
    { id: 'cable_row_60',      name: 'Single Arm Cable Row Panca 60',    trackE1rm: true,  anatomicalZone: 'shoulders', ytUrl: 'https://youtu.be/pYcpY20QaE8' },
    { id: 'cable_row',         name: 'Cable Row Seduto',                 trackE1rm: true,  anatomicalZone: 'shoulders', ytUrl: 'https://youtu.be/GZbfZ033f74' },
    { id: 'landmine_row',      name: 'Landmine Single Arm Row',          trackE1rm: true,  anatomicalZone: 'shoulders', ytUrl: 'https://youtu.be/s3Ye5n45-lQ' },
    { id: 'db_row',            name: 'DB One Arm Row',                   trackE1rm: true,  anatomicalZone: 'shoulders', ytUrl: 'https://youtu.be/pYcpY20QaE8' },
    { id: 'tbar_row',          name: 'T-Bar Row',                        trackE1rm: true,  anatomicalZone: 'lowerback',  ytUrl: 'https://youtu.be/j3Igk5nyZE4' },
    { id: 'chest_supp_row',    name: 'Chest Supported DB Row',           trackE1rm: true,  anatomicalZone: 'shoulders', ytUrl: 'https://youtu.be/Nx0TzjgsI-0' },
    { id: 'seal_row',          name: 'Seal Row',                         trackE1rm: true,  anatomicalZone: 'lowerback',  ytUrl: 'https://youtu.be/49Hbk_5fhoI' },
    { id: 'lat_pulldown_neutral', name: 'Lat Pulldown Neutral Grip',     trackE1rm: true,  anatomicalZone: 'shoulders', ytUrl: 'https://youtu.be/kVB6SlEyjQM' },
    { id: 'lat_pulldown_narrow',  name: 'Lat Pulldown Presa Stretta',    trackE1rm: true,  anatomicalZone: 'shoulders', ytUrl: 'https://youtu.be/0rzMziYkK7k' },
    { id: 'neutral_pullup',    name: 'Neutral Grip Pull-Up',             trackE1rm: true,  anatomicalZone: 'shoulders', ytUrl: 'https://youtu.be/A3kl7Do0a3g' },
    { id: 'inverted_row',      name: 'Inverted Row (Australian Pull-Up)', trackE1rm: false, anatomicalZone: 'shoulders', ytUrl: 'https://youtu.be/5Vy6mjhXg7s' },
    { id: 'machine_row',       name: 'Machine Row',                      trackE1rm: true,  anatomicalZone: 'shoulders', ytUrl: 'https://youtu.be/QXy1bfxMae0' },
    { id: 'high_row',          name: 'High Row Cavi',                    trackE1rm: true,  anatomicalZone: 'shoulders', ytUrl: 'https://youtu.be/Q9VuYU3tF9Q' },
    { id: 'pendlay_row',       name: 'Pendlay Row',                      trackE1rm: true,  anatomicalZone: 'lowerback', ytUrl: 'https://youtu.be/T3N-TO4reLQ' },
    { id: 'meadows_row',       name: 'Meadows Row',                      trackE1rm: true,  anatomicalZone: 'lowerback', ytUrl: 'https://youtu.be/s3Ye5n45-lQ' },
    { id: 'ez_bar_row',        name: 'EZ Bar Row',                       trackE1rm: true,  anatomicalZone: 'lowerback', ytUrl: 'https://youtu.be/j3Igk5nyZE4' },
    { id: 'cable_pullover',    name: 'Cable Pullover',                   trackE1rm: false, anatomicalZone: 'shoulders', ytUrl: 'https://youtu.be/ZhPOEQJRzBU' },
    { id: 'single_arm_lat',    name: 'Single-Arm Lat Pulldown',          trackE1rm: true,  anatomicalZone: 'shoulders', ytUrl: 'https://youtu.be/kVB6SlEyjQM' },
    { id: 'dead_hang',         name: 'Dead Hang',                        trackE1rm: false, anatomicalZone: 'shoulders', ytUrl: 'https://youtu.be/eGo4IYlbE5g' },
    { id: 'archer_row',          name: 'Archer Row',                       trackE1rm: true,  anatomicalZone: 'lowerback', ytUrl: 'https://youtu.be/Nx0TzjgsI-0' },
    { id: 'underhand_row',       name: 'Underhand BB Row (Yates Row)',      trackE1rm: true,  anatomicalZone: 'lowerback', ytUrl: 'https://youtu.be/T3N-TO4reLQ' },
    { id: 'wide_grip_pullup',    name: 'Wide Grip Pull-Up',                trackE1rm: true,  anatomicalZone: 'shoulders', ytUrl: 'https://youtu.be/eGo4IYlbE5g' },
    { id: 'w_pull',              name: 'Prone W Raise',                    trackE1rm: false, anatomicalZone: 'shoulders', ytUrl: 'https://youtu.be/xcV4SsEIn0I' },
    { id: 'renegade_row',        name: 'Renegade Row (DB)',                 trackE1rm: true,  anatomicalZone: 'lowerback', ytUrl: 'https://youtu.be/pYcpY20QaE8' },
    { id: 'face_pull_band',      name: 'Band Face Pull',                   trackE1rm: false, anatomicalZone: 'shoulders', ytUrl: 'https://youtu.be/eIq5CB9JfKE' },

    // ── LEGACCI / GAMBE ──────────────────────────────────────
    { id: 'back_squat',        name: 'Back Squat',                       trackE1rm: true,  anatomicalZone: 'knees',      ytUrl: 'https://youtu.be/bEv6CCg2BC8' },
    { id: 'front_squat',       name: 'Front Squat',                      trackE1rm: true,  anatomicalZone: 'knees',      ytUrl: 'https://youtu.be/m4ytaCJZpl0' },
    { id: 'goblet_squat',      name: 'Goblet Squat',                     trackE1rm: true,  anatomicalZone: 'knees',      ytUrl: 'https://youtu.be/MxsFDhcyFyE' },
    { id: 'hack_squat',        name: 'Hack Squat',                       trackE1rm: true,  anatomicalZone: 'knees',      ytUrl: 'https://youtu.be/hglQExHCM9Q' },
    { id: 'leg_press',         name: 'Leg Press 45',                     trackE1rm: true,  anatomicalZone: 'knees',      ytUrl: 'https://youtu.be/YyvSfVjQeL0' },
    { id: 'sumo_squat',        name: 'Sumo Squat',                       trackE1rm: true,  anatomicalZone: 'knees',      ytUrl: 'https://youtu.be/RKyiGw8Vyg0' },
    { id: 'bulgarian_lunges',  name: 'Bulgarian Lunges',                 trackE1rm: true,  anatomicalZone: 'knees',      ytUrl: 'https://youtu.be/2C-uNgKwPLE' },
    { id: 'back_lunges',       name: 'Back Lunges',                      trackE1rm: true,  anatomicalZone: 'knees',      ytUrl: 'https://youtu.be/QOVaHwm-Q6U' },
    { id: 'walking_lunges',    name: 'Walking Lunges',                   trackE1rm: false, anatomicalZone: 'knees',      ytUrl: 'https://youtu.be/L8fvypPrzzs' },
    { id: 'reverse_lunge',     name: 'Reverse Lunge',                    trackE1rm: true,  anatomicalZone: 'knees',      ytUrl: 'https://youtu.be/xrPteyQLGAo' },
    { id: 'step_up',           name: 'Step Up Single Leg',               trackE1rm: true,  anatomicalZone: 'knees',      ytUrl: 'https://youtu.be/WCFCdxzFBa4' },
    { id: 'box_jump',          name: 'Box Jump',                         trackE1rm: false, anatomicalZone: 'knees',      ytUrl: 'https://youtu.be/52r_Ul5k03g' },
    { id: 'broad_jump',        name: 'Broad Jump',                       trackE1rm: false, anatomicalZone: 'knees',      ytUrl: 'https://youtu.be/7Du1KbwCdUk' },
    { id: 'leg_curl',          name: 'Leg Curl',                         trackE1rm: false, anatomicalZone: 'knees',      ytUrl: 'https://youtu.be/1Tq3QdYUuHs' },
    { id: 'nordic_curl',       name: 'Nordic Curl',                      trackE1rm: false, anatomicalZone: 'knees',      ytUrl: 'https://youtu.be/Yn7aqLkeF0U' },
    { id: 'leg_ext',           name: 'Leg Extension',                    trackE1rm: false, anatomicalZone: 'knees',      ytUrl: 'https://youtu.be/YyvSfVjQeL0' },
    { id: 'calf_raise',        name: 'Calf Raise',                       trackE1rm: false, anatomicalZone: 'ankles',     ytUrl: 'https://youtu.be/JbyjNymZOt0' },
    { id: 'seated_calf',       name: 'Seated Calf Raise',                trackE1rm: false, anatomicalZone: 'ankles',     ytUrl: 'https://youtu.be/1Tq3QdYUuHs' },
    { id: 'tibialis_raise',    name: 'Tibialis Raise',                   trackE1rm: false, anatomicalZone: 'ankles',     ytUrl: 'https://youtu.be/xs7wTPl28CE' },
    { id: 'box_squat',         name: 'Box Squat',                        trackE1rm: true,  anatomicalZone: 'knees',      ytUrl: 'https://youtu.be/u87j5n6ClC8' },
    { id: 'split_squat',       name: 'Split Squat',                      trackE1rm: true,  anatomicalZone: 'knees',      ytUrl: 'https://youtu.be/2C-uNgKwPLE' },
    { id: 'lateral_lunge',     name: 'Lateral Lunge',                    trackE1rm: false, anatomicalZone: 'knees',      ytUrl: 'https://youtu.be/VYMwJERueAI' },
    { id: 'single_leg_press',  name: 'Leg Press Singola Gamba',          trackE1rm: true,  anatomicalZone: 'knees',      ytUrl: 'https://youtu.be/ZYDTJaAM-gE' },
    { id: 'hip_abduction',     name: 'Hip Abduction Machine',            trackE1rm: false, anatomicalZone: 'knees',      ytUrl: 'https://youtu.be/xbb4pU42CG4' },
    { id: 'hip_adduction',     name: 'Hip Adduction Machine',            trackE1rm: false, anatomicalZone: 'knees',      ytUrl: 'https://youtu.be/HPR_Opslke0' },
    { id: 'cable_kickback',    name: 'Cable Glute Kickback',             trackE1rm: false, anatomicalZone: 'lowerback',  ytUrl: 'https://youtu.be/bVrmtCI00Ys' },
    { id: 'single_leg_calf',   name: 'Single Leg Calf Raise',            trackE1rm: false, anatomicalZone: 'ankles',     ytUrl: 'https://youtu.be/ElcvJ0kjt6c' },
    { id: 'standing_leg_curl', name: 'Leg Curl in Piedi',                trackE1rm: false, anatomicalZone: 'knees',      ytUrl: 'https://youtu.be/CZVTv9T_Ml8' },
    { id: 'sissy_squat',       name: 'Sissy Squat',                      trackE1rm: false, anatomicalZone: 'knees',      ytUrl: 'https://youtu.be/AYN-U5nZieY' },
    { id: 'safety_bar_squat',  name: 'Safety Bar Squat',                 trackE1rm: true,  anatomicalZone: 'knees',      ytUrl: 'https://youtu.be/u87j5n6ClC8' },
    { id: 'zercher_squat',     name: 'Zercher Squat',                    trackE1rm: true,  anatomicalZone: 'knees',      ytUrl: 'https://youtu.be/m4ytaCJZpl0' },
    { id: 'leg_press_calf',    name: 'Leg Press Calf Raise',             trackE1rm: false, anatomicalZone: 'ankles',     ytUrl: 'https://youtu.be/JbyjNymZOt0' },
    { id: 'tke',               name: 'Terminal Knee Extension (TKE)',    trackE1rm: false, anatomicalZone: 'knees',      ytUrl: 'https://youtu.be/xs7wTPl28CE' },
    { id: 'single_leg_ext',    name: 'Single Leg Extension',             trackE1rm: false, anatomicalZone: 'knees',      ytUrl: 'https://youtu.be/YyvSfVjQeL0' },
    { id: 'paused_squat',      name: 'Paused Squat',                     trackE1rm: true,  anatomicalZone: 'knees',      ytUrl: 'https://youtu.be/bEv6CCg2BC8' },
    { id: 'wall_squat',        name: 'Wall Sit / Wall Squat',            trackE1rm: false, anatomicalZone: 'knees',      ytUrl: 'https://youtu.be/MxsFDhcyFyE' },
    { id: 'reverse_nordic',    name: 'Reverse Nordic Curl',              trackE1rm: false, anatomicalZone: 'knees',      ytUrl: 'https://youtu.be/Yn7aqLkeF0U' },
    { id: 'cyclist_squat',       name: 'Cyclist Squat (Heels Elevated)',   trackE1rm: true,  anatomicalZone: 'knees',      ytUrl: 'https://youtu.be/eMjyvIQbn9M' },
    { id: 'hatfield_squat',      name: 'Hatfield Squat',                   trackE1rm: true,  anatomicalZone: 'knees',      ytUrl: 'https://youtu.be/u87j5n6ClC8' },
    { id: 'anderson_squat',      name: 'Anderson Squat',                   trackE1rm: true,  anatomicalZone: 'knees',      ytUrl: 'https://youtu.be/u87j5n6ClC8' },
    { id: 'donkey_calf',         name: 'Donkey Calf Raise',                trackE1rm: false, anatomicalZone: 'ankles',     ytUrl: 'https://youtu.be/JbyjNymZOt0' },
    { id: 'cable_leg_curl',      name: 'Cable Leg Curl',                   trackE1rm: false, anatomicalZone: 'knees',      ytUrl: 'https://youtu.be/CZVTv9T_Ml8' },
    { id: 'leg_press_wide',      name: 'Wide Stance Leg Press',            trackE1rm: true,  anatomicalZone: 'knees',      ytUrl: 'https://youtu.be/YyvSfVjQeL0' },
    { id: 'glute_kickback_mach', name: 'Glute Kickback Machine',           trackE1rm: false, anatomicalZone: 'lowerback',  ytUrl: 'https://youtu.be/bVrmtCI00Ys' },
    { id: 'lying_leg_curl',      name: 'Lying Leg Curl',                   trackE1rm: false, anatomicalZone: 'knees',      ytUrl: 'https://youtu.be/1Tq3QdYUuHs' },

    // ── HINGE / CATENA POSTERIORE ────────────────────────────
    { id: 'deadlift',          name: 'Stacco da Terra',                  trackE1rm: true,  anatomicalZone: 'lowerback',  ytUrl: 'https://youtu.be/AweC3UaM14o' },
    { id: 'sumo_deadlift',     name: 'Sumo Deadlift',                    trackE1rm: true,  anatomicalZone: 'lowerback',  ytUrl: 'https://youtu.be/TY_ofowC0DI' },
    { id: 'trap_bar',          name: 'Trap Bar Deadlift',                trackE1rm: true,  anatomicalZone: 'lowerback',  ytUrl: 'https://youtu.be/uMeWCIEes38' },
    { id: 'bb_rdl',            name: 'BB RDL',                           trackE1rm: true,  anatomicalZone: 'lowerback',  ytUrl: 'https://youtu.be/8WyNLtl0mfE' },
    { id: 'db_rdl',            name: 'DB Romanian Deadlift',             trackE1rm: true,  anatomicalZone: 'lowerback',  ytUrl: 'https://youtu.be/JCXUYuzwNrM' },
    { id: 'single_rdl',        name: 'Single Leg RDL',                   trackE1rm: true,  anatomicalZone: 'lowerback',  ytUrl: 'https://youtu.be/J1ojvq3ftqM' },
    { id: 'good_morning',      name: 'Good Morning',                     trackE1rm: true,  anatomicalZone: 'lowerback',  ytUrl: 'https://youtu.be/nWyx81AfTos' },
    { id: 'hip_thrust',        name: 'Hip Thrust Machine',               trackE1rm: true,  anatomicalZone: 'lowerback',  ytUrl: 'https://youtu.be/LM8XHLYJoYs' },
    { id: 'bb_hip_thrust',     name: 'Hip Thrust Bilanciere',            trackE1rm: true,  anatomicalZone: 'lowerback',  ytUrl: 'https://youtu.be/LM8XHLYJoYs' },
    { id: 'glute_bridge',      name: 'Glute Bridge',                     trackE1rm: false, anatomicalZone: 'lowerback',  ytUrl: 'https://youtu.be/wPM8icPu6H8' },
    { id: 'kb_swing',          name: 'Kettlebell Swing',                 trackE1rm: false, anatomicalZone: 'lowerback',  ytUrl: 'https://youtu.be/U7gOEqSM-0I' },
    { id: 'single_leg_hip_thrust', name: 'Single Leg Hip Thrust',        trackE1rm: true,  anatomicalZone: 'lowerback',  ytUrl: 'https://youtu.be/kpkg8r7dex4' },
    { id: 'cable_pull_through', name: 'Cable Pull Through',              trackE1rm: false, anatomicalZone: 'lowerback',  ytUrl: 'https://youtu.be/fbF4_pn_0xc' },
    { id: 'ghd_hip_ext',       name: 'GHD Hip Extension',                trackE1rm: false, anatomicalZone: 'lowerback',  ytUrl: 'https://youtu.be/-FRYZjXMHkA' },
    { id: 'kb_deadlift',       name: 'Kettlebell Deadlift',              trackE1rm: true,  anatomicalZone: 'lowerback',  ytUrl: 'https://youtu.be/T7Qb1xmKYWc' },
    { id: 'stiff_leg_dl',      name: 'Stiff-Leg Deadlift',               trackE1rm: true,  anatomicalZone: 'lowerback',  ytUrl: 'https://youtu.be/1uDiW5--rAE' },
    { id: 'banded_hip_thrust', name: 'Banded Hip Thrust',                trackE1rm: false, anatomicalZone: 'lowerback',  ytUrl: 'https://youtu.be/LM8XHLYJoYs' },
    { id: 'back_ext_45',       name: '45-Degree Back Extension',         trackE1rm: false, anatomicalZone: 'lowerback',  ytUrl: 'https://youtu.be/ph3pddpKzzw' },
    { id: 'snatch_grip_dl',    name: 'Snatch-Grip Deadlift',             trackE1rm: true,  anatomicalZone: 'lowerback',  ytUrl: 'https://youtu.be/AweC3UaM14o' },
    { id: 'deficit_deadlift',    name: 'Deficit Deadlift',                 trackE1rm: true,  anatomicalZone: 'lowerback',  ytUrl: 'https://youtu.be/AweC3UaM14o' },
    { id: 'rack_pull',           name: 'Rack Pull',                        trackE1rm: true,  anatomicalZone: 'lowerback',  ytUrl: 'https://youtu.be/uMeWCIEes38' },
    { id: 'b_stance_rdl',        name: 'B-Stance RDL',                     trackE1rm: true,  anatomicalZone: 'lowerback',  ytUrl: 'https://youtu.be/J1ojvq3ftqM' },
    { id: 'paused_deadlift',     name: 'Paused Deadlift',                  trackE1rm: true,  anatomicalZone: 'lowerback',  ytUrl: 'https://youtu.be/AweC3UaM14o' },

    // ── OLIMPICI / POTENZA ───────────────────────────────────
    { id: 'power_clean',       name: 'Power Clean',                      trackE1rm: true,  anatomicalZone: 'shoulders', ytUrl: 'https://youtu.be/-PG2KtOz-0k' },
    { id: 'hang_clean',        name: 'Hang Power Clean',                 trackE1rm: true,  anatomicalZone: 'shoulders', ytUrl: 'https://youtu.be/WCFCdxzFBa4' },
    { id: 'power_snatch',      name: 'Power Snatch',                     trackE1rm: true,  anatomicalZone: 'shoulders', ytUrl: 'https://youtu.be/vUbUbRNH2s0' },
    { id: 'push_press',        name: 'Push Press',                       trackE1rm: true,  anatomicalZone: 'shoulders', ytUrl: 'https://youtu.be/a8HQo8z20Uo' },
    { id: 'push_jerk',         name: 'Push Jerk',                        trackE1rm: true,  anatomicalZone: 'shoulders', ytUrl: 'https://youtu.be/wcvLdlPbnBE' },
    { id: 'med_ball_slam',     name: 'Med Ball Slam',                    trackE1rm: false, anatomicalZone: 'lowerback',  ytUrl: 'https://youtu.be/EsAhU1jHpiQ' },
    { id: 'med_ball_throw',    name: 'Med Ball Overhead Throw',          trackE1rm: false, anatomicalZone: 'shoulders', ytUrl: 'https://youtu.be/z1JiHB8a4PY' },
    { id: 'jump_squat',        name: 'Jump Squat',                       trackE1rm: false, anatomicalZone: 'knees',      ytUrl: 'https://youtu.be/CVaEhXotL7M' },
    { id: 'depth_jump',        name: 'Depth Jump',                       trackE1rm: false, anatomicalZone: 'knees',      ytUrl: 'https://youtu.be/fL66hVKR89Q' },
    { id: 'sled_push',         name: 'Sled Push',                        trackE1rm: false, anatomicalZone: 'knees',      ytUrl: 'https://youtu.be/YJbKlXj4WhI' },
    { id: 'sled_pull',         name: 'Sled Pull',                        trackE1rm: false, anatomicalZone: 'knees',      ytUrl: 'https://youtu.be/cBTlCeSiu-8' },
    { id: 'hang_snatch',       name: 'Hang Power Snatch',                trackE1rm: true,  anatomicalZone: 'shoulders', ytUrl: 'https://youtu.be/SpDPcj0W3Yw' },
    { id: 'clean_pull',        name: 'Clean Pull',                       trackE1rm: true,  anatomicalZone: 'lowerback',  ytUrl: 'https://youtu.be/xx8WkFrST2Y' },
    { id: 'split_jerk',        name: 'Split Jerk',                       trackE1rm: true,  anatomicalZone: 'shoulders', ytUrl: 'https://youtu.be/2GPA-cjUFnA' },
    { id: 'mb_chest_pass',     name: 'Med Ball Chest Pass',              trackE1rm: false, anatomicalZone: 'shoulders', ytUrl: 'https://youtu.be/68SjXgERIvk' },
    { id: 'mb_rotational',     name: 'Med Ball Rotational Throw',        trackE1rm: false, anatomicalZone: 'lowerback',  ytUrl: 'https://youtu.be/c7fB-K8Ih54' },
    { id: 'continuous_box_jump', name: 'Continuous Box Jump',            trackE1rm: false, anatomicalZone: 'knees',      ytUrl: 'https://youtu.be/fTpI4tgjci0' },
    { id: 'hurdle_jump',       name: 'Hurdle Jump',                      trackE1rm: false, anatomicalZone: 'knees',      ytUrl: 'https://youtu.be/0H_fXWTUSiY' },
    { id: 'horizontal_bound',  name: 'Horizontal Bound (Single)',        trackE1rm: false, anatomicalZone: 'knees',      ytUrl: 'https://youtu.be/LAFf_sKB0cg' },
    { id: 'muscle_clean',      name: 'Muscle Clean',                     trackE1rm: true,  anatomicalZone: 'shoulders',  ytUrl: 'https://youtu.be/xx8WkFrST2Y' },
    { id: 'hang_power_clean',  name: 'Hang Power Clean',                 trackE1rm: true,  anatomicalZone: 'lowerback',  ytUrl: 'https://youtu.be/-PG2KtOz-0k' },
    { id: 'power_jerk',        name: 'Power Jerk',                       trackE1rm: true,  anatomicalZone: 'shoulders',  ytUrl: 'https://youtu.be/wcvLdlPbnBE' },
    { id: 'triple_broad_jump', name: 'Triple Broad Jump',                trackE1rm: false, anatomicalZone: 'knees',      ytUrl: 'https://youtu.be/7Du1KbwCdUk' },
    { id: 'single_leg_hop',    name: 'Single-Leg Hop (for distance)',    trackE1rm: false, anatomicalZone: 'knees',      ytUrl: 'https://youtu.be/LAFf_sKB0cg' },
    { id: 'reactive_drop_jump', name: 'Reactive Drop Jump',             trackE1rm: false, anatomicalZone: 'knees',      ytUrl: 'https://youtu.be/fL66hVKR89Q' },
    { id: 'full_clean',          name: 'Full Squat Clean',                 trackE1rm: true,  anatomicalZone: 'shoulders',  ytUrl: 'https://youtu.be/xx8WkFrST2Y' },
    { id: 'full_snatch',         name: 'Full Squat Snatch',                trackE1rm: true,  anatomicalZone: 'shoulders',  ytUrl: 'https://youtu.be/vUbUbRNH2s0' },
    { id: 'overhead_squat',      name: 'Overhead Squat',                   trackE1rm: true,  anatomicalZone: 'shoulders',  ytUrl: 'https://youtu.be/SpDPcj0W3Yw' },
    { id: 'db_snatch',           name: 'Dumbbell Snatch',                  trackE1rm: true,  anatomicalZone: 'shoulders',  ytUrl: 'https://youtu.be/vUbUbRNH2s0' },
    { id: 'snatch_balance',      name: 'Snatch Balance',                   trackE1rm: true,  anatomicalZone: 'shoulders',  ytUrl: 'https://youtu.be/SpDPcj0W3Yw' },
    { id: 'clean_jerk',          name: 'Clean & Jerk',                     trackE1rm: true,  anatomicalZone: 'shoulders',  ytUrl: 'https://youtu.be/2GPA-cjUFnA' },

    // ── ISOLARE PETTO ────────────────────────────────────────
    { id: 'pec_fly',           name: 'Pec Fly',                          trackE1rm: false, anatomicalZone: 'shoulders', ytUrl: 'https://youtu.be/eozdVDA78K0' },
    { id: 'cable_fly',         name: 'Cable Fly',                        trackE1rm: false, anatomicalZone: 'shoulders', ytUrl: 'https://youtu.be/taI4XduLpTk' },
    { id: 'cable_fly_low',     name: 'Cable Fly Low-to-High',            trackE1rm: false, anatomicalZone: 'shoulders', ytUrl: 'https://youtu.be/eQ_NBB6OBH4' },
    { id: 'cable_fly_high',    name: 'Cable Fly High-to-Low',            trackE1rm: false, anatomicalZone: 'shoulders', ytUrl: 'https://youtu.be/8Um35Es-ROE' },

    // ── ISOLARE SPALLE ───────────────────────────────────────
    { id: 'lateral_raises',    name: 'Lateral Raises DB',                trackE1rm: false, anatomicalZone: 'shoulders', ytUrl: 'https://youtu.be/3VcKaXpzqRo' },
    { id: 'cable_delt',        name: 'Cable Delt Raises',                trackE1rm: false, anatomicalZone: 'shoulders', ytUrl: 'https://youtu.be/eihMRam0P2Q' },
    { id: 'front_raises',      name: 'Front Raises DB',                  trackE1rm: false, anatomicalZone: 'shoulders', ytUrl: 'https://youtu.be/CH9JzDStL3U' },
    { id: 'face_pull',         name: 'Face Pull',                        trackE1rm: false, anatomicalZone: 'shoulders', ytUrl: 'https://youtu.be/eIq5CB9JfKE' },
    { id: 'rear_delt_fly',     name: 'Rear Delt Fly',                    trackE1rm: false, anatomicalZone: 'shoulders', ytUrl: 'https://youtu.be/xcV4SsEIn0I' },
    { id: 'upright_row',       name: 'Upright Row',                      trackE1rm: false, anatomicalZone: 'shoulders', ytUrl: 'https://youtu.be/nwkLwMRHMQo' },
    { id: 'shrug',             name: 'Shrug Bilanciere',                 trackE1rm: false, anatomicalZone: 'shoulders', ytUrl: 'https://youtu.be/u9Lp_F3lyTU' },
    { id: 'cable_shrug',       name: 'Cable Shrug',                      trackE1rm: false, anatomicalZone: 'shoulders', ytUrl: 'https://youtu.be/12g2avOv7so' },
    { id: 'lateral_raise_machine', name: 'Lateral Raise Machine',        trackE1rm: false, anatomicalZone: 'shoulders', ytUrl: 'https://youtu.be/IropE3iOk2c' },
    { id: 'rear_delt_machine', name: 'Rear Delt Machine (Pec Dec Inverso)', trackE1rm: false, anatomicalZone: 'shoulders', ytUrl: 'https://youtu.be/dtwZQcV48vI' },
    { id: 'db_shrug',          name: 'DB Shrug',                         trackE1rm: false, anatomicalZone: 'shoulders', ytUrl: 'https://youtu.be/qvvJUKq7_sU' },
    { id: 'bent_over_lateral', name: 'Bent Over Lateral Raise',          trackE1rm: false, anatomicalZone: 'shoulders', ytUrl: 'https://youtu.be/0ZhJBg77g7Y' },

    // ── ISOLARE SCHIENA ──────────────────────────────────────
    { id: 'straight_arm_pd',   name: 'Straight Arm Pulldown',            trackE1rm: false, anatomicalZone: 'shoulders', ytUrl: 'https://youtu.be/3sNc3hgtyjM' },
    { id: 'pullover',          name: 'DB Pullover',                      trackE1rm: false, anatomicalZone: 'shoulders', ytUrl: 'https://youtu.be/ZhPOEQJRzBU' },
    { id: 'hyperextension',    name: 'Hyperextension',                   trackE1rm: false, anatomicalZone: 'lowerback',  ytUrl: 'https://youtu.be/CgbmrF-DRSE' },
    { id: 'reverse_hyper',     name: 'Reverse Hyperextension',           trackE1rm: false, anatomicalZone: 'lowerback',  ytUrl: 'https://youtu.be/uQqR1NHfsSU' },

    // ── ISOLARE BICIPITI ─────────────────────────────────────
    { id: 'bb_curl',           name: 'BB Curl',                          trackE1rm: false, anatomicalZone: 'elbows',     ytUrl: 'https://youtu.be/kwG2ipFRgfo' },
    { id: 'curl_db_45',        name: 'Curl DB Panca 45',                 trackE1rm: false, anatomicalZone: 'elbows',     ytUrl: 'https://youtu.be/sAq_ocpRh_I' },
    { id: 'hammer_curl',       name: 'Cable Hammer Curl',                trackE1rm: false, anatomicalZone: 'elbows',     ytUrl: 'https://youtu.be/TwD-YGVP4Bk' },
    { id: 'preacher_curl',     name: 'Preacher Curl',                    trackE1rm: false, anatomicalZone: 'elbows',     ytUrl: 'https://youtu.be/fIWP-FRFNU0' },
    { id: 'incline_curl',      name: 'Incline DB Curl',                  trackE1rm: false, anatomicalZone: 'elbows',     ytUrl: 'https://youtu.be/sAq_ocpRh_I' },
    { id: 'cable_curl',        name: 'Cable Curl',                       trackE1rm: false, anatomicalZone: 'elbows',     ytUrl: 'https://youtu.be/NFzTWp2qpiE' },
    { id: 'spider_curl',       name: 'Spider Curl',                      trackE1rm: false, anatomicalZone: 'elbows',     ytUrl: 'https://youtu.be/B1fVN5zOit4' },
    { id: 'zottman_curl',      name: 'Zottman Curl',                     trackE1rm: false, anatomicalZone: 'elbows',     ytUrl: 'https://youtu.be/ix2ue9PhxzE' },
    { id: 'concentration_curl', name: 'Concentration Curl',              trackE1rm: false, anatomicalZone: 'elbows',     ytUrl: 'https://youtu.be/ZcU2hN76UyA' },
    { id: 'ez_bar_curl',       name: 'EZ Bar Curl',                      trackE1rm: false, anatomicalZone: 'elbows',     ytUrl: 'https://youtu.be/5NsFLGUf0Fo' },
    { id: 'reverse_curl',      name: 'Reverse Curl',                     trackE1rm: false, anatomicalZone: 'elbows',     ytUrl: 'https://youtu.be/ypfd1kaI1AU' },
    { id: 'bayesian_curl',     name: 'Bayesian Cable Curl',              trackE1rm: false, anatomicalZone: 'elbows',     ytUrl: 'https://youtu.be/teiR8q8nCE8' },
    { id: 'drag_curl',         name: 'Drag Curl',                        trackE1rm: false, anatomicalZone: 'elbows',     ytUrl: 'https://youtu.be/K1baXRg-OG8' },

    // ── ISOLARE TRICIPITI ────────────────────────────────────
    { id: 'push_down',         name: 'Push Down Cavi',                   trackE1rm: false, anatomicalZone: 'elbows',     ytUrl: 'https://youtu.be/2-LAMcpzODU' },
    { id: 'overhead_ext',      name: 'Overhead Extension Cavi Bassi',    trackE1rm: false, anatomicalZone: 'elbows',     ytUrl: 'https://youtu.be/tG2D4ernaBM' },
    { id: 'french_press',      name: 'French Press',                     trackE1rm: false, anatomicalZone: 'elbows',     ytUrl: 'https://youtu.be/d_KZxkY_0cM' },
    { id: 'skull_crusher',     name: 'Skull Crusher',                    trackE1rm: false, anatomicalZone: 'elbows',     ytUrl: 'https://youtu.be/d_KZxkY_0cM' },
    { id: 'db_kickback',       name: 'DB Tricep Kickback',               trackE1rm: false, anatomicalZone: 'elbows',     ytUrl: 'https://youtu.be/6SS6K3lAwZ8' },
    { id: 'dips_tri',          name: 'Dips (Tricipiti)',                  trackE1rm: false, anatomicalZone: 'elbows',     ytUrl: 'https://youtu.be/2z8JmcrW-As' },
    { id: 'cable_overhead_t',  name: 'Cable Overhead Tricep Extension',  trackE1rm: false, anatomicalZone: 'elbows',     ytUrl: 'https://youtu.be/tG2D4ernaBM' },
    { id: 'rope_pushdown',     name: 'Rope Pushdown',                    trackE1rm: false, anatomicalZone: 'elbows',     ytUrl: 'https://youtu.be/-KVa3M1uZfs' },
    { id: 'single_arm_pushdown', name: 'Single Arm Cable Pushdown',      trackE1rm: false, anatomicalZone: 'elbows',     ytUrl: 'https://youtu.be/Oy4-uJ35cQQ' },
    { id: 'wrist_curl',         name: 'Wrist Curl',                     trackE1rm: false, anatomicalZone: 'elbows',     ytUrl: 'https://youtu.be/kwG2ipFRgfo' },
    { id: 'reverse_wrist_curl', name: 'Reverse Wrist Curl',             trackE1rm: false, anatomicalZone: 'elbows',     ytUrl: 'https://youtu.be/ypfd1kaI1AU' },
    { id: 'cable_lateral_raise', name: 'Cable Lateral Raise',           trackE1rm: false, anatomicalZone: 'shoulders',  ytUrl: 'https://youtu.be/eihMRam0P2Q' },
    { id: 'pec_dec',            name: 'Pec Dec (Machine Fly)',           trackE1rm: false, anatomicalZone: 'shoulders',  ytUrl: 'https://youtu.be/dtwZQcV48vI' },
    { id: 'serratus_crunch',    name: 'Serratus Anterior Crunch',       trackE1rm: false, anatomicalZone: '',           ytUrl: 'https://youtu.be/aBd6T01PBqw' },
    { id: 'long_head_pushdown', name: 'Long Head Tricep Pushdown',      trackE1rm: false, anatomicalZone: 'elbows',     ytUrl: 'https://youtu.be/tG2D4ernaBM' },
    { id: 'hip_flexor_raise',    name: 'Hip Flexor Machine / Psoas March', trackE1rm: false, anatomicalZone: '',           ytUrl: 'https://youtu.be/Bfb-9dIWEr4' },
    { id: 'neck_flexion',        name: 'Neck Flexion',                     trackE1rm: false, anatomicalZone: '',           ytUrl: 'https://youtu.be/u9Lp_F3lyTU' },
    { id: 'neck_extension',      name: 'Neck Extension',                   trackE1rm: false, anatomicalZone: '',           ytUrl: 'https://youtu.be/u9Lp_F3lyTU' },
    { id: 'wrist_roller',        name: 'Wrist Roller',                     trackE1rm: false, anatomicalZone: 'elbows',     ytUrl: 'https://youtu.be/kwG2ipFRgfo' },
    { id: 'y_raise',             name: 'Y Raise (Trap-3)',                  trackE1rm: false, anatomicalZone: 'shoulders',  ytUrl: 'https://youtu.be/xcV4SsEIn0I' },
    { id: 'ext_rotation_cable',  name: 'External Rotation Cable',          trackE1rm: false, anatomicalZone: 'shoulders',  ytUrl: 'https://youtu.be/eUo48struNE' },

    // ── CORE / ADDOME ────────────────────────────────────────
    { id: 'crunch_cable',      name: 'Weighted Crunch with Cable',       trackE1rm: false, anatomicalZone: '',            ytUrl: 'https://youtu.be/aBd6T01PBqw' },
    { id: 'bicycle_crunch',    name: 'Bicycle Crunch',                   trackE1rm: false, anatomicalZone: '',            ytUrl: 'https://youtu.be/9FGilxCbdz8' },
    { id: 'hanging_leg_raise', name: 'Hanging Leg Raise',                trackE1rm: false, anatomicalZone: '',            ytUrl: 'https://youtu.be/Pr1ieGZ5atk' },
    { id: 'ab_wheel',          name: 'Ab Wheel Rollout',                 trackE1rm: false, anatomicalZone: 'lowerback',   ytUrl: 'https://youtu.be/nCh8VfWY5_g' },
    { id: 'plank',             name: 'Plank',                            trackE1rm: false, anatomicalZone: 'lowerback',   ytUrl: 'https://youtu.be/A2b2EmIg0dA' },
    { id: 'side_plank',        name: 'Side Plank',                       trackE1rm: false, anatomicalZone: 'lowerback',   ytUrl: 'https://youtu.be/K2VljzCC16g' },
    { id: 'pallof_press',      name: 'Pallof Press',                     trackE1rm: false, anatomicalZone: 'lowerback',   ytUrl: 'https://youtu.be/K9C0Ob-1r_E' },
    { id: 'dead_bug',          name: 'Dead Bug',                         trackE1rm: false, anatomicalZone: 'lowerback',   ytUrl: 'https://youtu.be/4XLEnwUr1d8' },
    { id: 'russian_twist',     name: 'Russian Twist',                    trackE1rm: false, anatomicalZone: '',            ytUrl: 'https://youtu.be/fPxO-FA8acM' },
    { id: 'cable_wood_chop',   name: 'Cable Woodchop',                   trackE1rm: false, anatomicalZone: '',            ytUrl: 'https://youtu.be/he4IhLc1d5k' },
    { id: 'v_up',              name: 'V-Up',                             trackE1rm: false, anatomicalZone: '',            ytUrl: 'https://youtu.be/iP2fjvG0g3w' },
    { id: 'toes_bar',          name: 'Toes to Bar',                      trackE1rm: false, anatomicalZone: '',            ytUrl: 'https://youtu.be/gBu16ijqpEg' },
    { id: 'ghd_situp',         name: 'GHD Sit-Up',                      trackE1rm: false, anatomicalZone: 'lowerback',   ytUrl: 'https://youtu.be/k1AHDQBuJ6o' },
    { id: 'dragon_flag',       name: 'Dragon Flag',                      trackE1rm: false, anatomicalZone: 'lowerback',   ytUrl: 'https://youtu.be/69AnMt9Fq9A' },
    { id: 'hollow_hold',       name: 'Hollow Body Hold',                 trackE1rm: false, anatomicalZone: 'lowerback',   ytUrl: 'https://youtu.be/HAfUt2Cco74' },
    { id: 'leg_raise_bench',   name: 'Leg Raise su Panca',               trackE1rm: false, anatomicalZone: 'lowerback',   ytUrl: 'https://youtu.be/l4kQd9eWclE' },
    { id: 'l_sit',             name: 'L-Sit',                            trackE1rm: false, anatomicalZone: 'lowerback',   ytUrl: 'https://youtu.be/IUZJoSP66HI' },
    { id: 'copenhagen_plank',  name: 'Copenhagen Plank',                 trackE1rm: false, anatomicalZone: 'knees',       ytUrl: 'https://youtu.be/YRRnnZsRs9U' },
    { id: 'hanging_windshield', name: 'Hanging Windshield Wiper',        trackE1rm: false, anatomicalZone: 'lowerback',   ytUrl: 'https://youtu.be/Aa_63nr9dzc' },
    { id: 'stir_pot',          name: 'Stir the Pot (Swiss Ball)',       trackE1rm: false, anatomicalZone: 'lowerback',   ytUrl: 'https://youtu.be/A2b2EmIg0dA' },
    { id: 'bb_rollout',        name: 'Barbell Rollout',                 trackE1rm: false, anatomicalZone: 'lowerback',   ytUrl: 'https://youtu.be/nCh8VfWY5_g' },
    { id: 'landmine_rotation', name: 'Landmine Rotation',              trackE1rm: false, anatomicalZone: 'lowerback',   ytUrl: 'https://youtu.be/he4IhLc1d5k' },
    { id: 'trx_fallout',       name: 'TRX/Ring Fallout',               trackE1rm: false, anatomicalZone: 'lowerback',   ytUrl: 'https://youtu.be/K9C0Ob-1r_E' },
    { id: 'suitcase_deadlift', name: 'Suitcase Deadlift',              trackE1rm: true,  anatomicalZone: 'lowerback',   ytUrl: 'https://youtu.be/tNHdx7pmrGI' },
    { id: 'loaded_carry_core', name: 'Loaded Carry for Core',          trackE1rm: false, anatomicalZone: 'lowerback',   ytUrl: 'https://youtu.be/Fkzk_RqlYig' },
    { id: 'spiderman_plank',     name: 'Spiderman Plank',                  trackE1rm: false, anatomicalZone: 'lowerback',  ytUrl: 'https://youtu.be/A2b2EmIg0dA' },
    { id: 'jefferson_curl',      name: 'Jefferson Curl',                   trackE1rm: false, anatomicalZone: 'lowerback',  ytUrl: 'https://youtu.be/ph3pddpKzzw' },
    { id: 'reverse_crunch',      name: 'Reverse Crunch',                   trackE1rm: false, anatomicalZone: '',           ytUrl: 'https://youtu.be/9FGilxCbdz8' },
    { id: 'oblique_crunch',      name: 'Oblique Crunch',                   trackE1rm: false, anatomicalZone: '',           ytUrl: 'https://youtu.be/fPxO-FA8acM' },
    { id: 'ghr',                 name: 'Glute Ham Raise (GHR)',             trackE1rm: false, anatomicalZone: 'knees',      ytUrl: 'https://youtu.be/-FRYZjXMHkA' },
    { id: 'weighted_plank',      name: 'Weighted Plank',                   trackE1rm: false, anatomicalZone: 'lowerback',  ytUrl: 'https://youtu.be/A2b2EmIg0dA' },

    // ── MOBILITÀ / ATTIVAZIONE ───────────────────────────────
    { id: 'hip_hinge',         name: 'Hip Hinge (tecnica)',              trackE1rm: false, anatomicalZone: 'lowerback',   ytUrl: 'https://youtu.be/068DbYEpKio' },
    { id: 'bird_dog',          name: 'Bird Dog',                         trackE1rm: false, anatomicalZone: 'lowerback',   ytUrl: 'https://youtu.be/T7M6Gj61DoE' },
    { id: 'cat_cow',           name: 'Cat-Cow',                          trackE1rm: false, anatomicalZone: 'lowerback',   ytUrl: 'https://youtu.be/kqnua4rHVVA' },
    { id: 'world_greatest',    name: 'World Greatest Stretch',           trackE1rm: false, anatomicalZone: '',            ytUrl: 'https://youtu.be/uIFKmkvgw8w' },
    { id: 'ankle_mob',         name: 'Ankle Mobilization',               trackE1rm: false, anatomicalZone: 'ankles',      ytUrl: 'https://youtu.be/evAAv0fXS2Q' },
    { id: 'hip_flex_stretch',  name: 'Hip Flexor Stretch',               trackE1rm: false, anatomicalZone: '',            ytUrl: 'https://youtu.be/Bfb-9dIWEr4' },
    { id: 'thoracic_rotation', name: 'Thoracic Rotation',                trackE1rm: false, anatomicalZone: '',            ytUrl: 'https://youtu.be/5TdmVlQe64c' },
    { id: 'band_pull_apart',   name: 'Band Pull Apart',                  trackE1rm: false, anatomicalZone: 'shoulders',   ytUrl: 'https://youtu.be/XPPfnSEATJA' },
    { id: 'scapular_pullup',   name: 'Scapular Pull Up',                 trackE1rm: false, anatomicalZone: 'shoulders',   ytUrl: 'https://youtu.be/Iv_V6oGBBQ0' },
    { id: 'Cuban_rotation',    name: 'Cuban Rotation',                   trackE1rm: false, anatomicalZone: 'shoulders',   ytUrl: 'https://youtu.be/eUo48struNE' },
    { id: 'couch_stretch',     name: 'Couch Stretch',                    trackE1rm: false, anatomicalZone: 'knees',       ytUrl: 'https://youtu.be/WKo4APrwfXQ' },
    { id: 'hip_90_90',         name: '90/90 Hip Stretch',                trackE1rm: false, anatomicalZone: 'lowerback',   ytUrl: 'https://youtu.be/ebZtd1B44QE' },
    { id: 'squat_to_stand',    name: 'Squat to Stand',                   trackE1rm: false, anatomicalZone: 'knees',       ytUrl: 'https://youtu.be/EgLQxPsQ93w' },
    { id: 'cossack_squat',     name: 'Cossack Squat',                    trackE1rm: false, anatomicalZone: 'knees',       ytUrl: 'https://youtu.be/d4IPCXI8GQc' },
    { id: 'foam_roller_thoracic', name: 'Foam Roller Thoracic Extension', trackE1rm: false, anatomicalZone: 'lowerback',  ytUrl: 'https://youtu.be/1LKd8e9QJ0w' },
    { id: 'wall_hip_flexor',   name: 'Wall Hip Flexor Stretch',          trackE1rm: false, anatomicalZone: 'lowerback',   ytUrl: 'https://youtu.be/ca54fyiIq2I' },
    { id: 'pigeon_stretch',    name: 'Pigeon Stretch',                  trackE1rm: false, anatomicalZone: 'lowerback',   ytUrl: 'https://youtu.be/WKo4APrwfXQ' },
    { id: 'shoulder_dislocates', name: 'Shoulder Dislocates (Band)',    trackE1rm: false, anatomicalZone: 'shoulders',   ytUrl: 'https://youtu.be/8lDC4Ri9zAQ' },
    { id: 'deep_squat_hold',   name: 'Deep Squat Hold',                 trackE1rm: false, anatomicalZone: 'knees',       ytUrl: 'https://youtu.be/EgLQxPsQ93w' },
    { id: 'hamstring_floss',   name: 'Active Hamstring Floss',          trackE1rm: false, anatomicalZone: 'knees',       ytUrl: 'https://youtu.be/ebZtd1B44QE' },
    { id: 'pec_doorway',       name: 'Pec Minor Doorway Stretch',       trackE1rm: false, anatomicalZone: 'shoulders',   ytUrl: 'https://youtu.be/XPPfnSEATJA' },
    { id: 'ankle_calf_stretch', name: 'Ankle/Calf Mobility',            trackE1rm: false, anatomicalZone: 'ankles',      ytUrl: 'https://youtu.be/evAAv0fXS2Q' },
    { id: 'hip_circle',          name: 'Hip Circles',                      trackE1rm: false, anatomicalZone: 'lowerback',  ytUrl: 'https://youtu.be/ebZtd1B44QE' },
    { id: 'figure_four',         name: 'Figure Four Stretch',              trackE1rm: false, anatomicalZone: 'lowerback',  ytUrl: 'https://youtu.be/WKo4APrwfXQ' },
    { id: 'lat_stretch',         name: 'Lat/Side Stretch',                 trackE1rm: false, anatomicalZone: 'shoulders',  ytUrl: 'https://youtu.be/3sNc3hgtyjM' },
    { id: 'neck_mob',            name: 'Neck Mobility Drills',             trackE1rm: false, anatomicalZone: '',           ytUrl: 'https://youtu.be/u9Lp_F3lyTU' },
    { id: 'wrist_ext_stretch',   name: 'Wrist Extension Stretch',          trackE1rm: false, anatomicalZone: 'elbows',     ytUrl: 'https://youtu.be/evAAv0fXS2Q' },
    { id: 'prone_hip_ext',       name: 'Prone Hip Extension',              trackE1rm: false, anatomicalZone: 'lowerback',  ytUrl: 'https://youtu.be/wPM8icPu6H8' },

    // ── CAMPO / CONDIZIONAMENTO ──────────────────────────────
    { id: 'sprint_10',         name: 'Sprint 10m',                       trackE1rm: false, anatomicalZone: '',            ytUrl: 'https://youtu.be/UtZWtHsOmsk' },
    { id: 'sprint_20',         name: 'Sprint 20m',                       trackE1rm: false, anatomicalZone: '',            ytUrl: 'https://youtu.be/UtZWtHsOmsk' },
    { id: 'sprint_30',         name: 'Sprint 30m',                       trackE1rm: false, anatomicalZone: '',            ytUrl: 'https://youtu.be/UtZWtHsOmsk' },
    { id: 'sprint_40',         name: 'Sprint 40m',                       trackE1rm: false, anatomicalZone: '',            ytUrl: 'https://youtu.be/UtZWtHsOmsk' },
    { id: 'tempo_run_200',     name: 'Tempo Run 200m',                   trackE1rm: false, anatomicalZone: '',            ytUrl: 'https://youtu.be/kVnyY17VS9Y' },
    { id: 'tempo_run_400',     name: 'Tempo Run 400m',                   trackE1rm: false, anatomicalZone: '',            ytUrl: 'https://youtu.be/kVnyY17VS9Y' },
    { id: 'agility_5_10_5',    name: '5-10-5 Agility Drill',            trackE1rm: false, anatomicalZone: '',            ytUrl: 'https://youtu.be/fZoJVVuqY3U' },
    { id: 't_test',            name: 'T-Test Agilità',                   trackE1rm: false, anatomicalZone: '',            ytUrl: 'https://youtu.be/k7xUw9Sjf-c' },
    { id: 'pro_agility',       name: 'Pro Agility Shuttle',              trackE1rm: false, anatomicalZone: '',            ytUrl: 'https://youtu.be/fZoJVVuqY3U' },
    { id: 'ladder_drill',      name: 'Ladder Drill',                     trackE1rm: false, anatomicalZone: '',            ytUrl: 'https://youtu.be/uJTYDAuyBWI' },
    { id: 'cone_drill',        name: 'Cone Drill',                       trackE1rm: false, anatomicalZone: '',            ytUrl: 'https://youtu.be/plnbMRosKLc' },
    { id: 'farmer_carry',      name: 'Farmer Carry',                     trackE1rm: false, anatomicalZone: 'shoulders',   ytUrl: 'https://youtu.be/Fkzk_RqlYig' },
    { id: 'yoke_carry',        name: 'Yoke Carry',                       trackE1rm: false, anatomicalZone: 'lowerback',   ytUrl: 'https://youtu.be/q0tTJwutC6A' },
    { id: 'battle_ropes',      name: 'Battle Ropes',                     trackE1rm: false, anatomicalZone: 'shoulders',   ytUrl: 'https://youtu.be/FInbOExDeU0' },
    { id: 'row_machine',       name: 'Vogatore (Rowing Machine)',         trackE1rm: false, anatomicalZone: 'lowerback',   ytUrl: 'https://youtu.be/QPvYrfyGHi8' },
    { id: 'assault_bike',      name: 'Assault Bike',                     trackE1rm: false, anatomicalZone: '',            ytUrl: 'https://youtu.be/0kzhFdDUUs0' },
    { id: 'ski_erg',           name: 'Ski Erg',                          trackE1rm: false, anatomicalZone: 'shoulders',   ytUrl: 'https://youtu.be/B0lIgT5PHc8' },
    { id: 'bike_sprint',       name: 'Bike Sprint',                      trackE1rm: false, anatomicalZone: '',            ytUrl: 'https://youtu.be/0kzhFdDUUs0' },
    { id: 'sprint_60',         name: 'Sprint 60m',                       trackE1rm: false, anatomicalZone: '',            ytUrl: 'https://youtu.be/kFLwmd0yzOU' },
    { id: 'fly_sprint',        name: 'Fly Sprint 20m',                   trackE1rm: false, anatomicalZone: '',            ytUrl: 'https://youtu.be/F7BlhM7k5o0' },
    { id: 'a_skip',            name: 'A-Skip',                           trackE1rm: false, anatomicalZone: '',            ytUrl: 'https://youtu.be/JPzYHi5iKmo' },
    { id: 'b_skip',            name: 'B-Skip',                           trackE1rm: false, anatomicalZone: '',            ytUrl: 'https://youtu.be/JPzYHi5iKmo' },
    { id: 'illinois_agility',  name: 'Illinois Agility Test',            trackE1rm: false, anatomicalZone: '',            ytUrl: 'https://youtu.be/CTndGKrdMbk' },
    { id: 'jump_rope',         name: 'Jump Rope (Corda)',                 trackE1rm: false, anatomicalZone: '',            ytUrl: 'https://youtu.be/ug7K-8X6pJk' },
    { id: 'burpee',            name: 'Burpee',                           trackE1rm: false, anatomicalZone: '',            ytUrl: 'https://youtu.be/wGvBfVeCNko' },
    { id: 'wall_ball',         name: 'Wall Ball (Med Ball)',              trackE1rm: false, anatomicalZone: 'shoulders',   ytUrl: 'https://youtu.be/U_wNNwNXKr8' },
    { id: 'sandbag_carry',     name: 'Sandbag Carry',                    trackE1rm: false, anatomicalZone: 'lowerback',   ytUrl: 'https://youtu.be/PTpridy5fMY' },
    { id: 'overhead_carry',    name: 'Overhead Carry',                   trackE1rm: false, anatomicalZone: 'shoulders',   ytUrl: 'https://youtu.be/1fGijWfRrCE' },
    { id: 'suitcase_carry',    name: 'Suitcase Carry',                   trackE1rm: false, anatomicalZone: 'lowerback',   ytUrl: 'https://youtu.be/tNHdx7pmrGI' },
    { id: 'bear_crawl',        name: 'Bear Crawl',                       trackE1rm: false, anatomicalZone: 'lowerback',   ytUrl: 'https://youtu.be/U3Y58Kyw7Xw' },
    { id: 'resisted_sprint',   name: 'Resisted Sprint (Sled)',           trackE1rm: false, anatomicalZone: '',            ytUrl: 'https://youtu.be/cBTlCeSiu-8' },
    { id: 'tuck_jump',         name: 'Tuck Jump',                        trackE1rm: false, anatomicalZone: 'knees',       ytUrl: 'https://youtu.be/0H_fXWTUSiY' },
    { id: 'bounding',          name: 'Bounding Multi-Direzionale',       trackE1rm: false, anatomicalZone: 'knees',       ytUrl: 'https://youtu.be/CVaEhXotL7M' },
    { id: 'stair_sprint',      name: 'Stair Sprint',                     trackE1rm: false, anatomicalZone: '',            ytUrl: 'https://youtu.be/UtZWtHsOmsk' },
    { id: 'kb_complex',        name: 'Kettlebell Complex',                trackE1rm: false, anatomicalZone: '',            ytUrl: 'https://youtu.be/U7gOEqSM-0I' },
    { id: 'prowler_push',      name: 'Prowler Push',                     trackE1rm: false, anatomicalZone: '',            ytUrl: 'https://youtu.be/YJbKlXj4WhI' },
    { id: 'tire_flip',         name: 'Tire Flip',                        trackE1rm: false, anatomicalZone: 'lowerback',   ytUrl: 'https://youtu.be/PTpridy5fMY' },
    { id: 'slam_ball',         name: 'Slam Ball',                        trackE1rm: false, anatomicalZone: 'lowerback',   ytUrl: 'https://youtu.be/EsAhU1jHpiQ' },
    { id: 'hill_sprint',         name: 'Hill Sprint',                      trackE1rm: false, anatomicalZone: '',           ytUrl: 'https://youtu.be/UtZWtHsOmsk' },
    { id: 'shuttle_run',         name: 'Shuttle Run',                      trackE1rm: false, anatomicalZone: '',           ytUrl: 'https://youtu.be/fZoJVVuqY3U' },
    { id: 'altitude_drop',       name: 'Altitude Drop',                    trackE1rm: false, anatomicalZone: 'knees',      ytUrl: 'https://youtu.be/fL66hVKR89Q' },
    { id: 'rowing_interval',     name: 'Rowing Intervals',                 trackE1rm: false, anatomicalZone: 'lowerback',  ytUrl: 'https://youtu.be/QPvYrfyGHi8' },
    { id: 'cycling_interval',    name: 'Cycling Intervals',                trackE1rm: false, anatomicalZone: '',           ytUrl: 'https://youtu.be/0kzhFdDUUs0' },
    { id: 'kb_snatch',           name: 'KB Snatch',                        trackE1rm: false, anatomicalZone: 'shoulders',  ytUrl: 'https://youtu.be/U7gOEqSM-0I' },
    { id: 'db_complex',          name: 'Dumbbell Complex',                 trackE1rm: false, anatomicalZone: '',           ytUrl: 'https://youtu.be/U7gOEqSM-0I' },
    { id: 'rope_climb',          name: 'Rope Climb',                       trackE1rm: false, anatomicalZone: 'shoulders',  ytUrl: 'https://youtu.be/eGo4IYlbE5g' },
];

// ─────────────────────────────────────────────────────────────
// STATO APPLICAZIONE
// DB è un oggetto condiviso: le mutazioni di proprietà (push,
// assegnazione di chiavi) sono visibili a tutti gli importatori.
// Non riassegnare DB stesso — usa replaceDB() per sincronizzare
// i dati caricati dal cloud/localStorage.
// ─────────────────────────────────────────────────────────────
export const DB = {
    athletes:          [],
    sessions:          [],
    schedules:         {},
    mesocycles:        [],
    injuries:          [],
    wellness:          { sleep:4, stress:2, sore:2, motiv:4, cycle:'N/A', weight:'', bf:'' },
    wellnessByAthlete: {},   // { [athleteId]: { sleep, sore, readinessScore } } — ultimo check-in per atleta
    messages:          {},   // { [athleteId]: [msg, ...] } — messaggi diretti coach ↔ atleta
    macroPlans:        {},   // { [athleteId]: { weeks, plan: [{week, phase, targetSessions, notes}] } }
    nutrition:         {},   // { [athleteId]: [{ date, kcal, proteine, carboidrati, grassi, note }] }
    nutritionTargets:  {}    // { [athleteId]: { kcal, proteine, carboidrati, grassi } }
};

export function replaceDB(data) {
    DB.athletes   = data.athletes   || [];
    DB.sessions   = data.sessions   || [];
    DB.schedules  = data.schedules  || {};
    DB.mesocycles = data.mesocycles || [];
    DB.injuries   = data.injuries   || [];
    if (data.wellness)          DB.wellness          = data.wellness;
    if (data.wellnessByAthlete) DB.wellnessByAthlete = data.wellnessByAthlete;
    if (data.messages)          DB.messages          = data.messages;
    if (data.macroPlans)        DB.macroPlans        = data.macroPlans;
    if (data.nutrition)         DB.nutrition         = data.nutrition;
    if (data.nutritionTargets)  DB.nutritionTargets  = data.nutritionTargets;
}

// Stato primitivo raccolto in un oggetto per permettere mutazioni
// visibili a tutti i moduli che importano appState.
export const appState = {
    selAthId:            '',
    curPanel:            'dashboard',
    edSessId:            '',
    pwRpe:               0,
    pwStars:             0,
    currentProgExIndex:  null,
    saveDbTimeout:       null,
    calWeekOffset:       0,
    // billing
    coachPlan:           'free',
    coachAthleteLimit:   3,
    coachSubStatus:      'inactive',
    coachPeriodEnd:      null,
    // branding / team
    brandName:           null,
    brandColor:          '#f97316',
    brandLogoUrl:        null,
    coachRole:           'head',
    headCoachId:         null,
};
